In [1]:
import pandas as pd
import numpy as np

## OneHotEncoder (category_encoders)

In [20]:
from category_encoders.one_hot import OneHotEncoder

In [21]:
data = ['Blue','Red','Brown','Yellow', np.nan]

In [22]:
ohe = OneHotEncoder()
ohe.fit(data)
ohe.transform(data)

0_1  0_2  0_3  0_4  0_5  0_-1
0    1    0    0    0    0     0
1    0    1    0    0    0     0
2    0    0    1    0    0     0
3    0    0    0    1    0     0
4    0    0    0    0    1     0

In [25]:
data_test = ['Blue','Red','Yellow','Green']

In [26]:
ohe.transform(data_test)

0_1  0_2  0_3  0_4  0_5  0_-1
0    1    0    0    0    0     0
1    0    1    0    0    0     0
2    0    0    0    1    0     0
3    0    0    0    0    0     0

## OneHotEncoder (scikit-learn)

In [27]:
import sklearn.preprocessing 

In [28]:
ohe = sklearn.preprocessing.OneHotEncoder()

In [30]:
# this does not work 
#ohe.fit(data)

In [40]:
data = ['Blue','Red','Brown','Yellow']

In [37]:
# need to use LabelEncoder first
le = sklearn.preprocessing.LabelEncoder()
le.fit_transform(data)
data_ = le.fit_transform(data).reshape(-1,1)
data_ = ohe.fit_transform(data_)

In [38]:
data_.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

....or use LableBinarizer

In [41]:
le = sklearn.preprocessing.LabelBinarizer()
le.fit(data)
le.transform(data)

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

**apparently not working with Pipelines**
https://github.com/scikit-learn/scikit-learn/issues/12720

## DictVectorizer

In [16]:
df = pd.read_csv('../data/house_train.csv')
df = df[['BsmtCond']]

In [17]:
df['BsmtCond'].unique()

array(['TA', 'Gd', nan, 'Fa', 'Po'], dtype=object)

In [18]:
df_dict = list(df.to_dict(orient='records'))

In [19]:
df_dict[:18]

[{'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'Gd'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': 'TA'},
 {'BsmtCond': nan}]

In [161]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer()
dv.fit(df_dict)
dv.transform(df_dict).toarray()

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

## get_dummies

In [138]:
pd.get_dummies(data)

Blue  Brown  Red  Yellow
0     1      0    0       0
1     0      0    1       0
2     0      1    0       0
3     0      0    0       1